

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SECRET_KEY=supersecretassignmentkey
      - DJANGO_DEBUG=True

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api/tasks/
    depends_on:
      - backend